### ISSUE TITLE
check version error

### ISSUE THREAD

**Issue by pupuliao** [pupuliao/JNovelDownloader#11]
frame.popVersionAlert(option); 

will print 

開始下載檔案: https://sourceforge.net/projects/jnoveldownload/filesjavax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
取得網頁html時發生錯誤....
等待一秒嘗試重新下載....
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at JNovelDownloader.Kernel.DownloadThread.run(DownloadThread.java:157)

**Comment by NemoChenTW** [comment]
Same problem on DownloadThread.run() with line:157 connection.connect();
Seems SSLException is the root cause. 

Log message is show as follows.

> 開始下載檔案: https://sourceforge.net/projects/jnoveldownload/files取得網頁html時發生錯誤....
等待一秒嘗試重新下載....
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at JNovelDownloader.Kernel.DownloadThread.run(DownloadThread.java:157)
